
export const CHECK_AUTH = 'checkAuth'
export const LOGIN = 'login'
export const LOGOUT = 'logout'
export const REGISTER = 'register'
export const UPDATE_USER = 'updateUser'
export const FETCH_BOOKS = 'fetchBooks'
export const FETCH_BOOK = 'fetchBook'
export const RETURN_BOOK = 'returnBook'
export const NEW_BOOK = 'newBook'
