export const FETCH_END = 'setBooks'
export const FETCH_START = 'setLoading'
export const PURGE_AUTH = 'logOut'
export const SET_BOOK = 'setBook'
export const SET_AUTH = 'setUser'
export const SET_ERROR = 'setError'
